import { chromium, devices } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({executablePath:'/opt/pw-browsers/chromium'}).catch(()=>chromium.launch());
const c = await b.newContext({...devices['Pixel 7'],acceptDownloads:true,permissions:['clipboard-read','clipboard-write']}); await c.addInitScript(()=>{ navigator.canShare=undefined; window.open=(u)=>{ window.__opened=u; return null; }; });
const p=await c.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message)); const ok=(c,m)=>console.log((c?'✔ ':'✘ ')+m);
await p.goto('http://localhost:8765/schicht/'); await p.waitForTimeout(700);
for(let i=0;i<6 && await p.isVisible('#onb');i++){ await p.locator('#onbbox button.pri').last().tap(); await p.waitForTimeout(200); }
await p.evaluate(()=>{ S.name='Malik'; S.rots=[{id:'r',name:'x',start:'2026-01-05',pattern:['F','F','F','F',null,null,null]}]; S.guide={hide:true,pickhide:true}; S.newsSeen=9; addVac('2026-11-09','2026-11-19'); save(); show('urlaub'); document.querySelector('#toast').hidden=true; });
await p.waitForTimeout(200);
await p.locator('.sharebtn',{hasText:'Monatsplan'}).tap(); await p.waitForTimeout(200);
ok(await p.locator('#pan .mcal .mc').count()>=28 && await p.locator('#pan .shareico').isVisible(), 'Monatsplan: Vorschau des Kalenders + Teilen-Symbol oben rechts');
ok(await p.locator('#ask:not([hidden])').count()===0 && await p.evaluate(()=>!document.querySelectorAll('a[download]').length), 'Noch nichts geteilt – erst Vorschau');
await p.screenshot({path:'/tmp/claude-0/sh-month.png'});
await p.locator('#pan .mhead button').last().tap(); await p.waitForTimeout(150);
ok(/NOVEMBER|November/.test(await p.locator('#pan .mhead h2').innerText()), 'Blättern zum nächsten Monat');
await p.locator('#pan .shareico').tap(); await p.waitForTimeout(150);
const opts=await p.locator('#ask .askb button').allInnerTexts(); ok(opts.length===6 && /PDF/.test(opts[0]) && /WhatsApp/.test(opts[1]), 'Teilen-Symbol → Auswahl: '+opts.join(' | '));
await p.screenshot({path:'/tmp/claude-0/sh-menu.png'});
const [dl]=await Promise.all([p.waitForEvent('download'), p.locator('#ask .askb button').first().tap()]); ok(/\.pdf$/.test(dl.suggestedFilename()), 'PDF erstellt: '+dl.suggestedFilename());
await p.locator('#pan .shareico').tap(); await p.waitForTimeout(100); await p.locator('#ask .askb button',{hasText:'Als Text per WhatsApp'}).tap(); await p.waitForTimeout(100);
const wa=await p.evaluate(()=>decodeURIComponent(window.__opened||'')); ok(/^https:\/\/wa\.me\/\?text=Schichtplan November 2026 – Malik/.test(wa) && /Urlaub/.test(wa), 'WhatsApp-Text: '+wa.split('\n').slice(0,3).join(' / '));
await p.locator('#pan .seg button',{hasText:'Urlaubsliste'}).tap(); await p.waitForTimeout(150);
ok(/09\.11\.|9\.11\./.test(await p.locator('#pan .prev').innerText()) && /8 Tage/.test(await p.locator('#pan .prev').innerText()), 'Urlaubsliste-Vorschau: 9.11.–19.11., 8 Tage');
await p.locator('#pan .shareico').tap(); await p.waitForTimeout(100); await p.locator('#ask .askb button',{hasText:'kopieren'}).tap(); await p.waitForTimeout(200);
const clip=await p.evaluate(()=>navigator.clipboard.readText()); ok(/Mein Urlaub 2026 – Malik/.test(clip) && /8 Urlaubstage/.test(clip), 'Text kopiert: '+clip.split('\n').slice(0,2).join(' / '));
await p.locator('#pan .seg button',{hasText:'Jahr'}).tap(); await p.waitForTimeout(150); ok(await p.locator('#pan .years .mini').count()===12, 'Jahresplan-Vorschau mit 12 Monaten');
await p.screenshot({path:'/tmp/claude-0/sh-year.png'});
await p.evaluate(()=>{ closeSheet(); show('heute'); }); await p.locator('.qbtn',{hasText:'Plan teilen'}).tap(); await p.waitForTimeout(150);
ok(await p.locator('#pan .shareico').isVisible(), '„Plan teilen“ auf Heute öffnet auch die Vorschau');
ok(errs.length===0,'Keine Skriptfehler '+errs.join('|')); await b.close();
